env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  max-len: off
  react/prop-types: off
  require-jsdoc: off
  member-delimitter-style:
    - 2
    - multiline:
        delimiter: "semi"
        requireLast: true
    - singleline:
        delimiter: "semi"
        requireLast: true
settings:
  react:
    version: "detect"
