stages:
  - build
  - test
  - package
  - publish

build-web:
  stage: build
  image: node:16.13
  variables:
    DEFAULT_API_URL: $DEFAULT_API_URL
  script:
    - npm ci
    - npm run build-web
  artifacts:
    paths:
      - dist/

sonarqube:
  stage: test
  only:
    - main
  image: sonarsource/sonar-scanner-cli:latest
  allow_failure: true
  variables:
    SONAR_HOST_URL: https://sonar.sterul.com
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: 0
    GIT_STRATEGY: clone
  script:
    - npm ci
    - npm run build-web
    - sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.sources=src
      -Dsonar.login="$SONAR_TOKEN"
      -Dsonar.projectKey="$CI_PROJECT_NAME"
      -Dsonar.links.scm="$CI_PROJECT_URL"
      -Dsonar.scm.revision="$CI_COMMIT_SHA"
      -Dsonar.scm.disabled=False
      -Dsonar.projectVersion="$CI_PIPELINE_IID"

package-docker-qa:
  stage: package
  resource_group: qa
  needs:
    - job: build-web
      artifacts: true
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    REGISTRY_TAG: qa
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$REGISTRY_TAG --cache=true --cache-ttl=100h
  rules:
    - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"

publish-expo:
  stage: publish
  resource_group: qa
  image: node:16.13
  variables:
    EXPO_TOKEN: $EXPO_TOKEN
    DEFAULT_API_URL: $DEFAULT_API_URL
  script:
    - npm ci
    - npm run publish-expo -- --release-channel beta

build-android:
  stage: publish
  image: steve192/expo-turtle-builder
  variables:
    # Token not supported by turtle
    EXPO_USERNAME: $EXPO_USERNAME
    EXPO_PASSWORD: $EXPO_PASSWORD
    DEFAULT_API_URL: $DEFAULT_API_URL
  script:
    - npm ci
    - expo-turtle-builder --target android --format app-bundle
  artifacts:
    paths:
      - output/android*

publish-cluster:
  stage: publish
  needs: ["package-docker-qa"]
  trigger:
    project: opencookbook/opencookbook-docker
    branch: main
