#!/usr/bin/env node
// Turns the Fluent Emoji the shopping list shows into WebP images the app bundles. Runs on every Metro
// start (see metro.config.js) and renders only when the names or the icon set changed; the images and
// their map are generated, never committed.
//
//   node scripts/shopping-icons.mjs                          render what shoppingIconNames.json lists
//   node scripts/shopping-icons.mjs --from-catalogue <path>  first take the names from an apiserver checkout
import crypto from 'node:crypto';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import sharp from 'sharp';

const SIZE = 96;

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const shopping = path.join(root, 'src', 'helper', 'shopping');
const namesFile = path.join(shopping, 'shoppingIconNames.json');
const outDir = path.join(root, 'assets', 'shopping-icons');
const mapFile = path.join(shopping, 'shoppingIcons.generated.js');
const stampFile = path.join(outDir, '.stamp');

const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));
const require = createRequire(import.meta.url);
const iconSet = require('@iconify-json/fluent-emoji-flat/icons.json');
const iconSetVersion = require('@iconify-json/fluent-emoji-flat/package.json').version;

/** The catalogue names icons as Fluent does ("cut_of_meat"), Iconify in kebab case. */
const iconifyName = (fluentName) => fluentName.replace(/_/g, '-');

const catalogueArgument = process.argv.indexOf('--from-catalogue');
if (catalogueArgument >= 0) {
  const catalogue = path.join(path.resolve(process.argv[catalogueArgument + 1]), 'src', 'main', 'resources', 'catalogue');
  const names = new Set([
    ...readJson(path.join(catalogue, 'catalogue.json')).foods.map((food) => food.icon),
    ...readJson(path.join(catalogue, 'non-food.json')).items.map((item) => item.icon),
  ].filter(Boolean));
  fs.writeFileSync(namesFile, JSON.stringify([...names].sort(), null, 2) + '\n');
}

const names = [...new Set([
  ...readJson(namesFile),
  ...Object.values(readJson(path.join(shopping, 'aisleIcons.json'))),
])].sort();

const svgOf = (name) => {
  const icon = iconSet.icons[iconifyName(name)];
  if (!icon) {
    throw new Error(`Fluent Emoji Flat has no icon named ${name}`);
  }
  const width = icon.width ?? iconSet.width;
  const height = icon.height ?? iconSet.height;
  return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">${icon.body}</svg>`);
};

const stamp = crypto.createHash('sha256').update(JSON.stringify([names, iconSetVersion, SIZE])).digest('hex');
if (fs.existsSync(mapFile) && fs.existsSync(stampFile) && fs.readFileSync(stampFile, 'utf8') === stamp) {
  process.exit(0);
}

fs.rmSync(outDir, {recursive: true, force: true});
fs.mkdirSync(outDir, {recursive: true});
await Promise.all(names.map((name) => sharp(svgOf(name), {density: 300})
    .resize(SIZE, SIZE)
    .webp({lossless: true})
    .toFile(path.join(outDir, `${name}.webp`))));

fs.writeFileSync(mapFile, [
  '// Generated by scripts/shopping-icons.mjs from Fluent Emoji (MIT, Microsoft Corporation).',
  'module.exports = {',
  ...names.map((name) => `  '${name}': require('../../../assets/shopping-icons/${name}.webp'),`),
  '};',
  '',
].join('\n'));
fs.writeFileSync(stampFile, stamp);
console.log(`${names.length} shopping icons -> ${path.relative(root, outDir)}`);
