/** The path the web app is served under on every instance; the API stays at /api. Mirrors app.json's baseUrl. */
export const BASE_PATH = '/app';

/**
 * Removes a leading base path from a path, keeping query and hash. A no-op for paths outside it,
 * such as links of the custom scheme or of the retired address.
 *
 * @param {string} path the path of an incoming link
 * @return {string} the path as the screen config knows it
 */
export const stripBasePath = (path: string): string => {
  if (path === BASE_PATH) {
    return '/';
  }
  for (const boundary of ['/', '?', '#']) {
    if (path.startsWith(BASE_PATH + boundary)) {
      const rest = path.slice(BASE_PATH.length);
      return rest.startsWith('/') ? rest : `/${rest}`;
    }
  }
  return path;
};

/**
 * @param {string} path a path generated by React Navigation
 * @return {string} the path below the base path
 */
export const addBasePath = (path: string): string => BASE_PATH + (path.startsWith('/') ? path : `/${path}`);

interface StateLike {
  index?: number;
  routes: {path?: string, state?: StateLike}[];
}

/**
 * Puts the base path back on the stored path of the focused route. React Navigation echoes that
 * path into the address bar on the first load without asking getPathFromState, so a path parsed
 * from the stripped link would otherwise drop the prefix from the address bar.
 *
 * @param {StateLike} state a state parsed from a stripped path
 * @return {StateLike} the state with the base path on the focused route's path
 */
export const restoreBasePathInState = <T extends StateLike>(state: T): T => {
  const focused = state.index ?? state.routes.length - 1;
  const routes = state.routes.map((route, i) => {
    if (i !== focused) {
      return route;
    }
    if (route.state) {
      return {...route, state: restoreBasePathInState(route.state)};
    }
    return typeof route.path === 'string' ? {...route, path: addBasePath(stripBasePath(route.path))} : route;
  });
  return {...state, routes};
};
